name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '11', '17', '21' ]

    steps:
    - uses: actions/checkout@v7

    - name: Setup Java
      uses: actions/setup-java@v5
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'

    - name: Install Clojure CLI
      uses: DeLaGuardo/setup-clojure@13
      with:
        cli: 1.12.5.1654

    - name: Cache m2 repository
      uses: actions/cache@v6
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/deps.edn') }}
        restore-keys: |
          ${{ runner.os }}-m2-

    - name: Run tests
      run: clojure -X:test
