name: Format and Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7

    - name: Setup Java
      uses: actions/setup-java@v5
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Install clojure tools
      uses: DeLaGuardo/setup-clojure@13
      with:
        clj-kondo: 2026.05.25
        cljfmt: 0.16.4

    - name: Format check
      run: cljfmt check src test

    - name: Lint check
      run: clj-kondo --lint src test
